#pragma once
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

namespace VampireSurvivorGameplayTags
{
	VAMPIRESURVIVORCLONE_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Enemy tags
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Beholder);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Cactus);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_ChestMonster);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Mushroom);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Slime);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_SwarmFish);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_SwarmInsect);
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Turtle);

	// Player Character (Avatar) tags
	VAMPIRESURVIVORCLONE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hero_Antonio);
	
}
